spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chauki
    redis:
      url: redis://localhost:6379

chauki:
  cors:
    allowed-origins: http://localhost:5173

logging:
  level:
    io.chauki: DEBUG
